project_name: sqlitr2

before:
  hooks:
    - go mod tidy

dist: dist-darwin

builds:
  - main: .
    binary: {{ .ProjectName }}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: binary
