env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy

builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm64
    prebuilt:
      path: dist-{{ .Os }}/sqlitr2_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/sqlitr2{{ .Ext }}
    binary: sqlitr2

archives:
  -
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

release:
  github:
    owner: neilotoole
    name: sqlitr2
  draft: false
  prerelease: auto



brews:
  -
    homepage: "https://github.com/neilotoole/sqlitr2"
    description: "sqlitr2 is a trivial Go/CGo SQLite CLI"
    license: MIT
    tap:
      # Repository owner template. (templateable)
      owner: neilotoole
      # Repository name. (templateable)
      name: homebrew-sqlitr2

    commit_author:
      name: neilotoole
      email: neilotoole@apache.org

    install: |
      bin.install "sqlitr2"
    test: |
      system "#{bin}/sqlitr2 --version"

scoop:
  bucket:
    owner: neilotoole
    name: sqlitr2
  homepage: "https://github.com/neilotoole/sqlitr2"
  description: "sqlitr2 is a trivial Go/CGo SQLite CLI"
  license: MIT
  commit_author:
    name: neilotoole
    email: neilotoole@apache.org

nfpms:
  -
    formats:
      - deb
      - rpm
    vendor: "neilotoole"
    homepage: "https://github.com/neilotoole/sqltir2"
    maintainer: "neilotoole@apache.org"
    description: "sqlitr2 is a trivial Go/CGo SQLite CLI"
    license: "MIT"

furies:
  # Upload deb and rpm to fury.io. Requires that envar $FURY_TOKEN be set.
  - account: neilotoole
