project_name: sqlitr2

before:
  hooks:
    - go mod tidy

dist: dist-linux

builds:
  -
    main: .
    binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-static
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: binary
