project_name: sqlitr2

before:
  hooks:
    - go mod tidy

builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm64
    prebuilt:
      path: dist-{{ .Os }}/{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/{{ .ProjectName }}{{ .Ext }}
    binary: {{ .ProjectName }}

archives:
  -
    replacements:
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

release:
  github:
    owner: neilotoole
    name: {{ .ProjectName }}
  draft: false
  prerelease: auto

brews:
  -
    homepage: "https://github.com/neilotoole/{{ .ProjectName }}"
    description: "{{ .ProjectName }} is a trivial Go/CGo SQLite CLI"
    license: MIT
    tap:
      owner: neilotoole
      name: homebrew-{{ .ProjectName }}

    commit_author:
      name: neilotoole
      email: neilotoole@apache.org

    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      system "#{bin}/{{ .ProjectName }} --version"

scoop:
  bucket:
    owner: neilotoole
    name: {{ .ProjectName }}
  homepage: "https://github.com/neilotoole/{{ .ProjectName }}"
  description: "{{ .ProjectName }} is a trivial Go/CGo SQLite CLI"
  license: MIT
  commit_author:
    name: neilotoole
    email: neilotoole@apache.org

nfpms:
  -
    formats:
      - apk
      - deb
      - rpm
    vendor: "neilotoole"
    homepage: "https://github.com/neilotoole/{{ .ProjectName }}"
    maintainer: "neilotoole@apache.org"
    description: "{{ .ProjectName }} is a trivial Go/CGo SQLite CLI"
    license: "MIT"

furies:
  # Upload deb and rpm to fury.io. Requires that envar $FURY_TOKEN be set.
  - account: neilotoole
