before:
  hooks:
    - go mod tidy

dist: dist-windows

builds:
  - main: .
    binary: sqlitr2
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
#      - -linkmode external -extldflags -static
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: binary
