before:
  hooks:
    - go mod tidy

dist: dist-linux

builds:
  -
    main: .
    binary: sqlitr2
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
#      - -linkmode external -extldflags -static
#      - -extldflags
      - -linkmode external
      - -static
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - format: binary
