env:
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy

builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: windows
        goarch: arm64
    prebuilt:
      path: dist-{{ .Os }}/sqlitr2_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/sqlitr2{{ .Ext }}
    binary: sqlitr2

archives:
  -
    replacements:
      darwin: macos
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  skip: true

release:
  github:
    owner: neilotoole
    name: sqlitr2
  draft: false
  prerelease: auto



brews:
  -
    homepage: "https://github.com/neilotoole/sqlitr2"
    description: "sqlitr2 is a trivial Go/CGo SQLite CLI"
    license: MIT
    tap:
      # Repository owner template. (templateable)
      owner: neilotoole
      # Repository name. (templateable)
      name: homebrew-sqlitr2

    commit_author:
      name: neilotoole
      email: neilotoole@apache.org

    install: |
      bin.install "sqlitr2"
    test: |
      system "#{bin}/sqlitr2 --version"

scoop:
  bucket:
    owner: neilotoole
    name: sqlitr2
  homepage: "https://github.com/neilotoole/sqlitr2"
  description: "sqlitr2 is a trivial Go/CGo SQLite CLI"
  license: MIT
  commit_author:
    name: neilotoole
    email: neilotoole@apache.org

#
#nfpms:
#  -
#    builds: ['build_linux']
#    formats:
#      - deb
#      - rpm
#    vendor: "neilotoole"
#    homepage: "https://github.com/neilotoole/sqltir"
#    maintainer: "neilotoole@apache.org"
#    description: "sqlitr is a trivial Go/CGo SQLite CLI"
#    license: "MIT"
#

#
#snapcrafts:
#  # For this to work, login to snapcraft.
#  # - On macOS, "brew install snapcraft", then "snapcraft login".
#  # - Or just use neilotoole/xcgo: https://github.com/neilotoole/xcgo/wiki/Snapcraft
#  -
#    builds:
#      - build_linux
#    name: sqlitr2
#    summary: "Trivial SQLite query tool to demonstrate neilotoole/xcgo"
#    description: |
#      sqlitr is a trivial query tool for SQLite. It was created as a demonstration for neilotoole/xcgo, which is a Go cross-compiling docker builder image.
#    grade: stable
#    confinement: strict
#    publish: true
#    license: MIT
#    base: core18
#    apps:
#      sqlitr2:
#        # If your app requires extra permissions to work outside of its default
#        # confined space, declare them here.
#        # You can read the documentation about the available plugs and the
#        # things they allow:
#        # https://snapcraft.io/docs/reference/interfaces.
#        #
#        # Declare "home" and "network" plugs to grant access to
#        # the user home dir, and the network
#        plugs: ["home", "network"]
#
#dockers:
#  -
#    goos: linux
#    goarch: amd64
#    builds:
#      - build_linux
#    image_templates:
#      - "neilotoole/sqlitr2:{{ .Version }}"
#    extra_files:
#      - README.md
#      - LICENSE
#      - testdata/example.sqlite
